// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTLInwKhjRBTuvSxJeuJfxTiKSzr9tfo',
    appId: '1:693766899636:web:90910b70fcf04eddccd4e1',
    messagingSenderId: '693766899636',
    projectId: 'robotics-inventory-bcc2a',
    authDomain: 'robotics-inventory-bcc2a.firebaseapp.com',
    storageBucket: 'robotics-inventory-bcc2a.appspot.com',
    measurementId: 'G-PMM3WR9KBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlowhPfZdPIo0mVZPgnCCsngKyTTXP3Y',
    appId: '1:693766899636:android:5e62a1457c99d660ccd4e1',
    messagingSenderId: '693766899636',
    projectId: 'robotics-inventory-bcc2a',
    storageBucket: 'robotics-inventory-bcc2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6aV2eSn2fPOpFJRfn7ewcoEdwQmuyUWI',
    appId: '1:693766899636:ios:9227db05c9a9a3dbccd4e1',
    messagingSenderId: '693766899636',
    projectId: 'robotics-inventory-bcc2a',
    storageBucket: 'robotics-inventory-bcc2a.appspot.com',
    iosClientId: '693766899636-1f6ckuereese9hpto37bvda59ifkt78g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6aV2eSn2fPOpFJRfn7ewcoEdwQmuyUWI',
    appId: '1:693766899636:ios:9227db05c9a9a3dbccd4e1',
    messagingSenderId: '693766899636',
    projectId: 'robotics-inventory-bcc2a',
    storageBucket: 'robotics-inventory-bcc2a.appspot.com',
    iosClientId: '693766899636-1f6ckuereese9hpto37bvda59ifkt78g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
